# Состояния разговора
(
    WAITING_FOR_TEXT, WAITING_FOR_LOCATION, SELECTING_REQUEST,
    WAITING_FOR_ADMIN_CODE, WAITING_FOR_BROADCAST, WAITING_FOR_REPORT_PERIOD,
    ADMIN_VIEW_REQUESTS, ADMIN_VIEW_REQUEST_DETAIL, ADMIN_CHANGE_STATUS,
    ADMIN_REPLY_TO_REQUEST, ADMIN_SELECT_REQUEST
) = range(11)